### ISSUE TITLE
Need to update README with 

### ISSUE THREAD

**Issue by sergeyf** [allenai/SPECTER2_0#2]
A lot of the readme has `specter2_0` but it's called `specter_plus_plus`. 

Please also update the readme here, as it has the same issues: https://huggingface.co/allenai/specter_plus_plus

Finally, please merge: https://huggingface.co/allenai/specter/discussions/7

**Comment by amanpreet692** [comment]
HuggingFace names have been updated to allenai/specter2* as in [here](https://huggingface.co/models?search=allenai/specter-2) and your update has been merged in the Specter model page as well.
Leaving the repo as it is since everything has already been pushed for Timo.
