### ISSUE TITLE
Excessive memory usage 

### ISSUE THREAD

**Issue by zilch42** [allenai/SPECTER2_0#7]
Hi there, 

I'm struggling to embed documents with this model due to the amount of memory it seems to require. I'm trying to run it on an NVIDIA A100 GPU. I can run the 2 papers in the code example but I can't run a group of 2000 abstracts, or the newsgroups dataset shown below. 

```
from transformers import AutoTokenizer, AutoModel
from sklearn.datasets import fetch_20newsgroups

# load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained('allenai/specter2_base')

#load base model
model = AutoModel.from_pretrained('allenai/specter2_base')

#load the adapter(s) as per the required task, provide an identifier for the adapter in load_as argument and activate it
model.load_adapter("allenai/specter2", source="hf", load_as="specter2", set_active=True)

docs = fetch_20newsgroups(subset='all')['data']

# preprocess the input
model = model.to("cuda")
inputs = tokenizer(docs, padding=True, truncation=True,
                        return_tensors="pt", return_token_type_ids=False, max_length=512).to("cuda")
output = model(**inputs)
# take the first token in the batch as the embedding
embeddings = output.last_hidden_state[:, 0, :].detach().cpu().numpy()
```

```
RuntimeError: CUDA out of memory. Tried to allocate 27.61 GiB (GPU 0; 31.74 GiB total capacity; 28.27 GiB already allocated; 2.21 GiB free; 28.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Is that amount of memory usage expected? I'm a little surprised as I can run larger `sentence_transformer` models like `BAAI/bge-large-en` on the same dataset and they take up far less VRAM. 

I'm not sure if it's not batching properly...? 
Is there anything else I can do to reduce the memory usage?

**Comment by amanpreet692** [comment]
2000 docs at once sounds a lot! you are probably better off doing inference on smaller chunks.
Iirc from my experiments, on a 48G GPU I can embed upto 64 docs of max size of 512 tokens at once.
Please divide your input into batches of 16,32,64 ... so on and see what works out best for you!

**Comment by zilch42** [comment]
Thanks @amanpreet692, I don't think I realised I had to do the batching myself, coming from using sentence_transformers which handles it for me
