### ISSUE TITLE
What's your score generation strategy when evaluated on MDCR benchmark?

### ISSUE THREAD

**Issue by Miracle-dz** [allenai/SPECTER2_0#9]
Hello! I have been trying to reproduce your results on MDCR(MAP: 38.0, R@5: 32.4) with SPECTER-2 Base. 

I used SPECTER-2 Base to generate 768-dimensional embeddings of every query and candidate paper according to title and abstract, but the proper strategy to **generate scores** between embeddings of query and candidate papers is unclear to me.

 I have tried dot, cosine similarity, and L2 distance, but none of them can produce the same result as you mentioned. 

Could you please show some details about your score strategy between query and candidate embeddings?  
I'll really appreciate it if you can provide more, such as a copy of source code！Thank You！

**Comment by amanpreet692** [comment]
Hello! Thanks for using the SPECTER2 model.

For generating the MDCR results, please follow the below steps:
i) Set up the MDCR repo at https://github.com/zoranmedic/mdcr and also download the test_split and test_data files in the root directory of the repo.
ii) Generating the scores json file: You can use https://github.com/allenai/scirepeval/blob/main/mdcr.py for that. Setup the SciRepEval repo as per given instructions. Assuming your MDCR root directory is one level up, run ``mdcr.py`` as follows:
```python 
python mdcr.py -m allenai/specter2_base
```
The script generates embeddings for the papers in ``mdcr_test_data.json`` and also calculates the negative L2 distance (higher is similar) for the query candidate pairs in ``mdcr_test.json`` and generates a reult file with the default name of ``scirepeval_mdcr.json``. Note: If you are running on a GPU environment the script should take 30 mins to run.
iii) Running the MDCR evaluation script: 
```python
cd ../mdcr
python evaluate.json --benchmark_file mdcr_test.json --scores_file ../scirepeval scirepeval_mdcr.json
```

Let us know if there are any queries.

**Comment by Miracle-dz** [comment]
Thank you for detailed reply！
